---
apiVersion: v1
kind: Pod
metadata:
  name: backend-service
  labels:
    app.kubernetes.io/name: "backend"
    app.kubernetes.io/component: "utility"
    app.kubernetes.io/version: "v1.0.0"
spec:
  containers:
    - image:  nginx:alpine
      name:  backend-container
--- 
apiVersion: v1
kind: Pod
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/name: "frotnend"
    app.kubernetes.io/component: "service"
    app.kubernetes.io/version: "v1.0.0"
spec:
  containers:
    - image:  nginx:alpine
      name:  frontend-container
---
apiVersion: v1
kind: Pod
metadata:
  name: loggin-service
  labels:
    app.kubernetes.io/name: "loggin"
    app.kubernetes.io/component: "utility"
    app.kubernetes.io/version: "v1.0.0"
spec:
  containers:
    - image:  alpine
      name:  loggin-container
      command: ["sh", "-c", "while true; do echo $(date) ' - Sidecar logging'; sleep 5; done"]
