apiVersion: v1
kind: Service
metadata:
  name: weatherapp-auth
  labels:
    app: weatherapp-auth
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: weatherapp-auth