apiVersion: v1
data:
  auth-password: cm9vdA==
  root-password: cm9vdA==
  secret-key: eGNvMHNyMGZoNGU1MngwM2c5bXY=
kind: Secret
metadata:
  creationTimestamp: "2024-11-30T21:13:38Z"
  name: mysql-secret
  namespace: default
  resourceVersion: "770"
  uid: 34e5c32e-2d9f-4dab-878f-e04837e4f70f
type: Opaque